<?php
$plugin_id = array('shop', 'backtop');
$app_settings_model = new waAppSettingsModel();
$app_settings_model->set($plugin_id, 'status', '1');
$app_settings_model->set($plugin_id, 'bg', '#ffffff');
$app_settings_model->set($plugin_id, 'bg2', '#ffffff');
$app_settings_model->set($plugin_id, 'border_color', '#ffffff');
$app_settings_model->set($plugin_id, 'border_size', '2');
$app_settings_model->set($plugin_id, 'border_radius', '10');
$app_settings_model->set($plugin_id, 'button_width', '100');
$app_settings_model->set($plugin_id, 'button_height', '50');
$app_settings_model->set($plugin_id, 'opacity', '0.8');
$app_settings_model->set($plugin_id, 'text_size', '16');
$app_settings_model->set($plugin_id, 'text', '&#9650;');
$app_settings_model->set($plugin_id, 'link_color', '#ffffff');
$app_settings_model->set($plugin_id, 'link_hover', '#dd0303');
$app_settings_model->set($plugin_id, 'position_ver', 'b');
$app_settings_model->set($plugin_id, 'position_hor', 'r');
$app_settings_model->set($plugin_id, 'pos_ver', '50');
$app_settings_model->set($plugin_id, 'pos_hor', '50');
