DROP TABLE IF EXISTS `shop_product_promo`;
CREATE TABLE IF NOT EXISTS `shop_product_promo` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`product_id` INT NOT NULL DEFAULT '0',
	`status` TINYINT NOT NULL DEFAULT '0',
	`datetime` DATETIME NOT NULL
) ENGINE = MYISAM DEFAULT CHARSET=utf8;
